name: 'ssh-agent-action'
description: 'Load ssh-key and start ssh-agent'
inputs:
  ssh_private_key:
    description: 'Private key'
    required: true
  ssh_auth_sock:
    description: 'Where to place SSH Agent socket'
    required: true
  ghes_host:
    description: "GHES server address"
    required: true
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path}}/action.sh
      shell: bash
      env:
        INPUT_GHES_HOST: ${{ inputs.ghes_host }}
        INPUT_SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
        INPUT_SSH_AUTH_SOCK: ${{ inputs.ssh_auth_sock }}
